release: python manage.py makemigrations --no-input
release: python django-postgres/manage.py migrate --no-input
# Uncomment if you need to collect static files
release: python manage.py collectstatic --no-input

web: gunicorn django-postgres.ratiba.wsgi --log-file -